### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AinzOoalGown-fun** [weblearnerhabib/Anti-Adblock-Script#1]
Hello , how we use it ?
it's html how to inject it into a web page ?
Thank you -_-

**Comment by weblearnerhabib** [comment]
Hi, Thank you for contact us. 
Myself "**Rishat**" onbehalf of Team "WebLearner".

You are right! if you wish to prevent Ad-blocker add-ons or extension to your website and force Ad-blocker then you should use our script. you have to download our script. and manually have to inject the script and css codes to your project.

you can also edit/modify our script or css code as well. we give 100% modification permission. 

wish that help you a lot.. if you have any query ping us. 

Regards,
"**Rishat**"
--------
OnBehalf of "TeamWebLearner"

**Comment by AinzOoalGown-fun** [comment]
> Hi, Thank you for contact us. Myself "**Rishat**" onbehalf of Team "WebLearner".
